language: java
jdk:
  - openjdk11

services:
  - docker

script:
  - ./gradlew build

after_success:
  - docker build -t lmj174/ssackthree:1.0 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lmj174/ssackthree:1.0
