name: deploy

on:
  release:
    types: [push]
  push:
    branches: [main]
    paths:
      - 'ssackthree_back/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ssackthree_back/gradlew
        shell: bash

      - name: Build with Gradle
        run: cd ssackthree_back && ./gradlew clean build -x test
        shell: bash

      - name: Build Docker image
        run:
          cd ssackthree_back
          docker build -t lmj174/ssackthree:1.0 .
          cd ..
        shell: bash

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push lmj174/ssackthree:1.0
        shell: bash

